### ISSUE TITLE
use `min` and `max` to describe min_parallelism and parallelism in JobSpec

### ISSUE THREAD

**Issue by zen-xu** [zen-xu/habitat#15]
new API will like
```yaml
apiVersion: batch.habitat/v1beta1
kind: Job
metadata:
  name: demo
spec:
  parallelism:
    min: 1
    max: 2
  template: ...
```

This will better express the association between the lower and upper bounds of parallelism than the original one.
