### ISSUE TITLE
Is it reasonable to support multi tasks defined in a single job

### ISSUE THREAD

**Issue by zen-xu** [zen-xu/habitat#6]
The core point is **` what's the boundary of a job? `**

1. manages tasks with one type?
2. manages tasks with multi types?

### Pros
- the implementation will be much easier, and we can refer to the implementation of [k8s job](https://kubernetes.io/docs/concepts/workloads/controllers/job/).
### Cons
- the job like Tensorflow(ps/worker) and Spark (driver/executor) will be much more difficult to adapt

### Pros
- the job like Tensorflow(ps/worker) will be much easier to adapt
### Cons
- how to handle `CoScheduling` between different types of tasks
- whether there are dependencies between different types of tasks

**Comment by zen-xu** [comment]
## Proposal for co-scheduling different jobs Plan 2(with one type)

Another way to help co-scheduling different jobs is to provide a mechanism to tell the scheduler.

### Add annotation
We can add the annotation to each co-scheduling job.

```yaml
---
apiVersion: habitat.dev/beta1
kind: Job
metadata:
  name: job1
  annotations:
    habitat.dev/co-scheduling-jobs: job1,job2   # add annotation to indicate job1 and job2 
                                                # should be co-scheduling
spec: ...
---
apiVersion: habitat.dev/beta1
kind: Job
metadata:
  name: job2
  annotations:
    habitat.dev/co-scheduling-jobs: job1,job2
spec: ...
```

**Comment by zen-xu** [comment]
Adopt `Proposal for co-scheduling different jobs Plan 2(with one type)`

**Comment by zen-xu** [comment]
I think a job with multi-type tasks is reasonable.

The core of the habitat scheduler is **co-scheduling**, where the minimum number of parallelism tasks determines the scheduling unit for each job.

for example

```yaml
apiVersion: habitat.dev/beta1
kind: Job
metadata:
  name: awesome
spec:
  tasks:
  - name: main
    cmd: [bash, run.sh]
    parallelism:
      min: 2
      max: 4
    resources:
      requests:
        cpu: 2
        memory: 2Gi
  - name: ps
    cmd: [bash, run.sh]
    parallelism:
      min: 1
      max: 2
    resources:
      requests:
        cpu: 1
        memory: 1Gi
```

Job `awesome` can only be scheduled if 2 `main` and 1 `ps` tasks can allocate enough resources
